common/models/TabelPutway.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "{{%tabel_putway}}".
 *
 * @property integer $putway_id
 * @property string $hu_number
 * @property string $to_lokasi
 * @property string $to_row
 * @property integer $to_level
 * @property string $refrence
 * @property string $create_at
 * @property string $update_at
 */
class TabelPutway extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tabel_putway}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_at',
                'updatedAtAttribute' => 'update_at',
                'value'=> new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hu_number'], 'string'],
            [['hu_number', 'to_lokasi', 'to_row', 'to_level', 'type_produk'], 'required'],
            [['hu_number'], 'unique'],
            [['to_level'], 'integer'],
            [['create_at', 'update_at'], 'safe'],
            [['to_lokasi', 'to_row', 'status'], 'string', 'max' => 50],
            [['refrence'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'putway_id' => Yii::t('app', 'Putway ID'),
            'type_produk' => Yii::t('app', 'Type Produk'),
            'hu_number' => Yii::t('app', 'Hu Number'),
            'to_lokasi' => Yii::t('app', 'To Lokasi'),
            'to_row' => Yii::t('app', 'To Row'),
            'to_level' => Yii::t('app', 'To Level'),
            'refrence' => Yii::t('app', 'Refrence'),
            'status' => Yii::t('app', 'Status'),
            'create_at' => Yii::t('app', 'Create At'),
            'update_at' => Yii::t('app', 'Update At'),
        ];
    }
}

backend/controllers/TabelPutwayController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\TabelPutway;
use common\models\TabelPutwaySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TabelPutwayController implements the CRUD actions for TabelPutway model.
 */
class TabelPutwayController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TabelPutway models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TabelPutwaySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TabelPutway model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TabelPutway model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TabelPutway();

        if ($model->load(Yii::$app->request->post())) {
            $status = 'scan';
            $model->status = $status;
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->putway_id]);
            }
            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TabelPutway model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $status = 'scan';
            $model->status = $status;
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->putway_id]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TabelPutway model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TabelPutway model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TabelPutway the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TabelPutway::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPutway_confirmation()
    {
        $data = TabelPutway::find()->where(['status' => 'scan']);
        $count = clone $data;
        $pages = new \yii\data\Pagination(['totalCount' => $count->count()]);
        $models = $data->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        if (isset($_POST['checkbox'])) {
            $status = 'done';
            $refrence = Yii::$app->request->post('refrence');
            foreach ($_POST['checkbox'] as $key => $checkbox) {
                $check = ($checkbox);
                $update = "UPDATE tabel_putway SET status = '$status', refrence = '$refrence' WHERE putway_id = '$check' ";

                $query = \Yii::$app->db->createCommand($update)->execute();
            }
            if ($query) {
                $modelDo = new \common\models\MasterDo();
                $modelDo->no_do = $refrence;
                $modelDo->save();
            }
            $this->redirect(['/site/index']);
        }
        return $this->render('putway', [
                'models' => $models,
                'pages' => $pages,
            ]);
    }

    public function actionEdit($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $status = 'scan';
            $model->status = $status;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Update Data Sukses');
                return $this->redirect(['putway_confirmation']);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
}

backend/views/tabel-putway/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model common\models\TabelPutway */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tabel-putway-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?php 
        $type = \common\models\MasterType::find()->all();
        $listType = \yii\helpers\ArrayHelper::map($type, 'produk_type', 'produk_type');
    ?>
    
    <?= $form->field($model, 'type_produk')->dropDownList($listType, ['prompt' => 'Pilih Produk']) ?>

    <?= $form->field($model, 'hu_number')->textInput() ?>
    
    <?php 
        $lokasi = \common\models\MasterLokasi::find()->orderBy('lokasi_name ASC')->all();
        $listLokasi = \yii\helpers\ArrayHelper::map($lokasi, 'lokasi_name', 'lokasi_name'); 
    ?>

    <?= $form->field($model, 'to_lokasi')->textInput() ?>

    <?php 
        $row = \common\models\MasterRow::find()->orderBy('name_row ASC')->all();
        $listRow = \yii\helpers\ArrayHelper::map($row, 'name_row', 'name_row'); 
    ?>    

    <?= $form->field($model, 'to_row')->dropDownList($listRow, ['prompt' => 'Pilih Row']) ?>

    <?= $form->field($model, 'to_level')->textInput() ?>

    <?php //$form->field($model, 'refrence')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/tabel-putway/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TabelPutwaySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tabel-putway-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'putway_id') ?>

    <?= $form->field($model, 'hu_number') ?>

    <?= $form->field($model, 'to_lokasi') ?>

    <?= $form->field($model, 'to_row') ?>

    <?= $form->field($model, 'to_level') ?>

    <?php // echo $form->field($model, 'refrence') ?>

    <?php // echo $form->field($model, 'create_at') ?>

    <?php // echo $form->field($model, 'update_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/tabel-putway/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\TabelPutway */

$this->title = Yii::t('app', 'Putway Proses');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tabel Putways'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tabel-putway-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tabel-putway/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\TabelPutwaySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Tabel Putways');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tabel-putway-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Tabel Putway'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions' => function ($model) {
            if ($model->status == 'scan') {
                return ['class' => 'success'];
            }
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'putway_id',
            [
                'attribute' => 'type_produk',
                'filter' => \kartik\widgets\Select2::widget([
                        'model' => $searchModel,
                        'attribute' => 'type_produk',
                        'data' => \yii\helpers\ArrayHelper::map(\common\models\MasterType::find()->all(), 'produk_type', 'produk_type'),
                        'options' => ['placeholder' => 'Select'],
                        'pluginOptions' => ['allowClear' => true]
                    ]),
                
            ],
            'hu_number:ntext',
            'to_lokasi',
            'to_row',
            'to_level',
            'refrence',
            [
                'attribute' => 'status',
                'format' => 'raw',
                'filter' => \kartik\widgets\Select2::widget([
                        'model' => $searchModel,
                        'attribute' => 'status',
                        'data' => [
                            'new' => 'new',
                            'scan' => 'scan',
                            'confirm' => 'confirm',
                            'done' => 'done'
                        ],
                        'options' => ['placeholder' => 'Select'],
                        'pluginOptions' => ['allowClear' => true]
                    ]),
                'value' => function ($model) {
                    if ($model->status === 'scan') {
                        return "<span class='label label-warning'>Scann</span>";
                    } elseif ($model->status === 'new') {
                        return "<span class='label label-success'>New</span>";
                    } elseif($model->status === 'confirm') {
                        return "<span class='label label-primary'>Confirm</span>";
                    } else {
                        return "<span class='label label-default'>done</span>";
                    }
                },
                
            ],
            //'create_at',
            // 'update_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/tabel-putway/putway.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

$this->title = Yii::t('app', 'Putway Confirm');
$this->params['breadcrumbs'][] = $this->title;
?>
<script type="text/javascript">
	function toggle(pilih) {
	  	checkboxes = document.getElementsByName('checkbox[]');
	  	for (var i = 0, n=checkboxes.length;i<n;i++) {
	    	checkboxes[i].checked = pilih.checked;
	  	}
	}
</script>
<h1><?= \yii\helpers\Html::encode($this->title); ?></h1>
<?php $form = ActiveForm::begin() ?>
<div class="form-group">
	<input type="text" class="form-control" name="refrence" placeholder="Refrence" required >
</div>
<table class="table table-bordered table-hover table-striped">
	<thead>
		<th><input type="checkbox" name="checkboxall" onClick="toggle(this)"></th>
		<th>No</th>
		<th>Type Produk</th>
		<th>HU Number</th>
		<th>To Lokasi</th>
		<th>action</th>
	</thead>
	<tbody>
	<?php 
		$no = 1;
		foreach ($models as $model) { ?>
			<tr>
				<td><input type="checkbox" name="checkbox[]" id="checkbox" value="<?php echo $model['putway_id']; ?>" /></td>
				<td><?php echo $no; ?></td>
				<td><?php echo $model->type_produk; ?></td>
				<td><?php echo $model->hu_number; ?></td>
				<td><?php echo $model->to_lokasi.'-'.$model->to_row.$model->to_level; ?></td>
				<td><?= Html::a('edit',['/tabel-putway/edit', 'id' => $model->putway_id]); ?></td>
			</tr>
		<?php $no++; } ?>
	</tbody>
</table>
<div class="form-group">
	<?= Html::submitButton('<i class="fa fa-spinner"></i>  Confirm', [ 'id' => 'update', 'class' => 'btn btn-primary']) ?>
</div>
<?php ActiveForm::end() ?>

backend/views/tabel-putway/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TabelPutway */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Tabel Putway',
]) . $model->putway_id;
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tabel Putways'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->putway_id, 'url' => ['view', 'id' => $model->putway_id]];
//$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="tabel-putway-update">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tabel-putway/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\TabelPutway */

$this->title = $model->putway_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tabel Putways'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tabel-putway-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->putway_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->putway_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'putway_id',
            'type_produk',
            'hu_number:ntext',
            'to_lokasi',
            'to_row',
            'to_level',
            'refrence',
            'status',
            'create_at',
            'update_at',
        ],
    ]) ?>

</div>