backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\UploadForm;
use common\models\MasterData;
use common\models\MasterDataSearch;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;
use common\models\SearchForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => [
                            'logout', 
                            'index', 
                            'upload', 
                            'tree', 
                            'data', 
                            'confirm', 
                            'search', 
                            'send',
                            'outbound',
                            'outbound_sugar',
                            'export',
                            'putway',
                            'export_do'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Function Untuk action confirmation STO
     *
     * @return string
     */

    protected function findModel($id)
    {
        if (($model = MasterData::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionExport()
    {
        $model = new \common\models\MasterSto();
        $request = Yii::$app->request;
        $db = Yii::$app->db;

        $no_sto = $request->post('no_sto');

        if (!is_null($no_sto)) {
            $customer = "FFI";
            $customer_code = 5;
            $tanggal = date("d/m/Y");
            $separator = "\t";
            $filename = "data_".$no_sto.".txt";
            $dataSearch = new MasterDataSearch();
            $query = \common\models\MasterData::find()->where(['no_sto' => $no_sto])->all();

            foreach ($query as $data) {
                echo 
                $customer.$separator.
                $customer_code.$separator.
                $tanggal.$separator.
                $no_sto.$separator.
                $separator.$separator.
                $data['produk'].$separator.
                $data['hu_number'].$separator.
                $data['quantity']."\r\n";
            }
            header('Content-type: text/plain');
            header('Content-Disposition: attachment; filename='.$filename);

            Yii::$app->end();      
        } 
        return $this->render('export', ['model' => $model]);
    }

    public function actionExport_do()
    {
        $model = new \common\models\MasterDo();
        $request = \Yii::$app->request;
        $db = \Yii::$app->db;

        $no_do = $request->post('no_do');

        if (!is_null($no_do)) {
            $separator = "\t";
            $filename = "data_".$no_do.".txt";
            $query = \common\models\TabelPutway::find()->where(['refrence' => $no_do])->all();

            foreach ($query as $data) {
                echo 
                $data['hu_number'].$separator.
                $data['to_lokasi'].$separator.
                $data['to_row'].$separator.
                $data['to_level'].$separator.
                $data['refrence'].$separator.
                $data['create_at'].$separator."\r\n";
            }
            header('Content-type: text/plain');
            header('Content-Disposition: attachment; filename='.$filename);

            Yii::$app->end();      
        }
        return $this->render('export-do', ['model' => $model]);
    }
    
    public function actionUpload()
    {
        $model = new UploadForm();

        if ($model->load(Yii::$app->request->post())) {
            $file = UploadedFile::getInstance($model, 'file');
            $filename = 'Data.'.$file->extension;
            $upload = $file->saveAs('uploads/'.$filename);

            if ($upload){
                define('CSV_PATH', 'uploads/');

                $csv_file = CSV_PATH.$filename;
                $filecsv = file($csv_file);
                print_r($filecsv);
                //die;

                foreach ($filecsv as $data) {

                    $modelnew = new MasterData();

                    $hasil = explode(",", $data);
                    $activity = $hasil[0];
                    $type = $hasil[1];
                    $produk = $hasil[2];
                    $description = $hasil[3];
                    $batch = $hasil[4];
                    $hu_number = $hasil[5];
                    $quantity = $hasil[6];
                    $no_pol =  $hasil[7];
                    $driver = $hasil[8];
                    $hu_number_key = substr($hu_number, -6);
                    $status = 'new';

                    $modelnew->activity  = $activity;
                    $modelnew->type_produk = $type;
                    $modelnew->produk = $produk;
                    $modelnew->description = $description;
                    $modelnew->batch  = $batch;
                    $modelnew->hu_number = $hu_number;
                    $modelnew->quantity = $quantity;
                    $modelnew->no_pol = $no_pol;
                    $modelnew->driver_name = $driver;
                    $modelnew->hu_number_key = $hu_number_key;
                    $modelnew->status = $status;

                    $modelnew->save(); 
                }

                unlink('uploads/'.$filename);
                Yii::$app->session->setFlash('success', '<span class="glyphicon glyphicon-info-sign"></span>  <b>Data Success di Upload</b>');
                return $this->redirect(['master-data/index']);
            } 
        } elseif (Yii::$app->request->isAjax) {
            return $this->renderAjax('upload', [
                'model' => $model,
            ]);
        }else {
            return $this->render('upload', [
                'model' => $model,
            ]);
        } 
    }

    public function actionSearch()
    {
        $searchModel = new MasterDataSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new MasterData();

        return $this->render('search', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
    }

    public function actionSend($hu_number)
    {
        $model = MasterData::find()->where(['hu_number' => $hu_number])->one();
        $count = MasterData::find()->where(['status' => 'scan'])->count();
        $status = 'scan';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Sukses Kirim data');

            return $this->redirect(['/site/search']);
        } else {
            return $this->render('create', [
                    'model' => $model,
                    $model->status = $status,
                ]);
        }
    }

    /**
     * Function untuk menampilkan data dari table master_data
     *
     * @return string
     */
    public function actionData()
    {
        $data = MasterData::find()->where(['status' => 'scan']);
        $countQuery = clone $data;
        $pages = new \yii\data\Pagination(['totalCount' => $countQuery->count()]);
        $models = $data->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        
        if (isset($_POST['checkbox'])) {
            $status = 'confirm';
            $no_pol = Yii::$app->request->post('no_pol');
            $nama_supir = Yii::$app->request->post('driver_name');
            foreach ($_POST['checkbox'] as $index => $checkbox) {
                $check = ($checkbox);
                $update = "UPDATE master_data SET status='$status', no_pol='$no_pol', driver_name='$nama_supir' WHERE id='$check' ";

                Yii::$app->db->createCommand($update)->execute();
            }
            $this->redirect(['/site/data']);
        }
        return $this->render('data', [
                'models' => $models,
                'pages' => $pages,
            ]);
    }

    public function actionOutbound()
    {
        $query = MasterData::find()->where(['activity' => 'outbound', 'type_produk' => 'FG', 'status' => 'confirm']);
        $countQuery = clone $query;

backend/views/site/_item.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin(); ?>
<table class="table table-hover table-bordered table-striped">
	<tr>
		<td><b>Produk</b></td>
		<td><?php echo $form->field($model, 'produk')->hiddenInput([
				'value' => $model['produk'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->produk; ?>
		</td>
	</tr>
	<tr>
		<td><b>Description</b></td>
		<td><?php echo $form->field($model, 'description')->hiddenInput([
				'value' => $model['description'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->description; ?>
		</td>
	</tr>
	<tr>
		<td><b>Hu NUmber</b></td>
		<td><?php echo $form->field($model, 'hu_number')->hiddenInput([
				'value' => $model['hu_number'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->hu_number; ?>
		</td>
	</tr>
	<tr>
		<td><b>Batch Number</b></td>
		<td><?php echo $form->field($model, 'batch')->hiddenInput([
				'value' => $model['batch'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->batch; ?>
		</td>
	</tr>
	<tr>
		<td><b>Quantity</b></td>
		<td><?php echo $form->field($model, 'quantity')->hiddenInput([
				'value' => $model['quantity'],
				'readOnly' => true
			])->label(false) ?>
			<?php echo $model->quantity; ?>
		</td>
	</tr>
</table>
<div class="form-group">
	<?= Html::a('Send', ['/site/send', 'hu_number' => $model->hu_number], ['class' => 'btn btn-warning']); ?>
</div>
<?php ActiveForm::end(); ?>

backend/views/site/_search.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin([
	'action' => ['search'], 
	'method' => 'get',
]); ?>

<?= $form->field($model, 'hu_number')->textInput(['class' => 'form-control', 'placeholder' => 'Masukan HU Number']) ?>
<div class="form-group">
	<?= Html::submitButton('Search', ['class' => 'btn btn-primary']); ?>
</div>

<?php ActiveForm::end(); ?>

backend/views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\MasterData */

$this->title = Yii::t('app', ' Scanning confirmation');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Master Datas'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="master-data-create">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->renderAjax('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/export-do.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

$this->title = Yii::t('app', 'Export Data Inbound');
$this->params['breadcrumbs'][] = $this->title;

?>

<?= Html::beginForm(['site/export_do'], 'post'); ?>
<p>Please fill out in sto number. We will take your requested.</p>
<div class="form-group">
	<div class="row">
		<div class="col-md-3">
			<label>Start Date</label>
			<?php $date = date("Y-m-d H:i:s"); ?>
			<?php
				echo yii\jui\DatePicker::widget( [
				// 'pluginOptions' => [
				// 'autoClose' => true,
				// 'format' => 'yyyy-mm-dd',
				// ],
				'options' => ['class' => 'form-control'],
				'value' => $date,
				'name' => 'datepicker-start',
				'dateFormat' => 'yyyy-MM-dd',
				'clientOptions' =>[
					'numberOfMonths' => 1,
					//'minDate' => '-1m',
					//'maxDate' => '+1m',
					'changeMonth' => true,
				]
			]) ?>
		</div>
		<div class="col-md-3">
			<label>End Date</label>
			<?php
				echo yii\jui\DatePicker::widget( [
				// 'pluginOptions' => [
				// 'autoClose' => true,
				// 'format' => 'yyyy-mm-dd',
				// ],
				'options' => ['class' => 'form-control'],
				'value' => $date,
				'name' => 'datepicker-end',
				'dateFormat' => 'yyyy-MM-dd',
				'clientOptions' =>[
					'numberOfMonths' => 1,
					//'minDate' => '-1m',
					//'maxDate' => '+1m',
					'changeMonth' => true,
				]
			]) ?>
		</div>
	</div>
</div>
<div class="form-group">
	<div class="row">
		<div class="col-md-6">
			<?php 
				$do = \common\models\MasterDo::find()->all();
				$listDo = \yii\helpers\ArrayHelper::map($do, 'no_do', 'no_do');
				// Without model and implementing a multiple select
				echo Select2::widget([
				    'name' => 'no_do',
				    'data' => $listDo,
				    'options' => [
				        'placeholder' => 'Pilih No Refrence',
				        'multiple' => false
				    ],
				    'pluginOptions' => [
				        'allowClear' => true
				    ],
				]);
			?>
			<?php 
				
			?>
			<!--<input type="text" name="no_sto" class="form-control" required >-->
		</div>
	</div>
</div>
<div class="form-group">
	<?= Html::submitButton('<i class="fa fa-download"></i>  Export', ['class' => 'btn btn-primary']) ?>	
</div>

<?= Html::endForm() ?>

backend/views/site/export.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

$this->title = Yii::t('app', 'Export Data Outbound');
$this->params['breadcrumbs'][] = $this->title;

?>

<?= Html::beginForm(['site/export'], 'post'); ?>
<p>Please fill out in sto number. We will take your requested.</p>
<div class="form-group">
	<div class="row">
		<div class="col-md-6">
			<?php 
				$sto = \common\models\MasterSto::find()->all();
				$listSto = \yii\helpers\ArrayHelper::map($sto, 'no_sto', 'no_sto');
				// Without model and implementing a multiple select
				echo Select2::widget([
				    'name' => 'no_sto',
				    'data' => $listSto,
				    'options' => [
				        'placeholder' => 'Pilih STO Number',
				        'multiple' => false
				    ],
				    'pluginOptions' => [
				        'allowClear' => true
				    ],
				]);
			?>
			<?php 
				
			?>
			<!--<input type="text" name="no_sto" class="form-control" required >-->
		</div>
	</div>
</div>
<div class="form-group">
	<?= Html::submitButton('<i class="fa fa-download"></i>  Export', ['class' => 'btn btn-primary']) ?>	
</div>

<?= Html::endForm() ?>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

backend/views/site/login-old.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Golden</b>App</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Sign in', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>
        <?php ActiveForm::end(); ?>
    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

backend/views/site/outbound-sugar.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Outbound Raw Material');
$this->params['breadcrumbs'][] = $this->title;

?>
<script type="text/javascript">
	function toggle(pilih) {
	  	checkboxes = document.getElementsByName('checkbox[]');
	  	for (var i = 0, n=checkboxes.length;i<n;i++) {
	    	checkboxes[i].checked = pilih.checked;
	  	}
	}
</script>
<?php $form = ActiveForm::begin(); ?>
	<div class="form-group">
		<input type="text" class="form-control" name="no_sto" placeholder="Masukan Nomor STO" required>
	</div>
	<div class="form-group">
	<?= Html::submitButton('<i class="fa fa-spinner"></i>  Confirm', [ 'id' => 'update', 'class' => 'btn btn-primary btn-sm']) ?>
	<?= Html::submitButton('<i class="fa fa-refresh"></i>  Refresh', [ 'id' => 'update', 'class' => 'btn btn-default btn-sm']) ?>
	</div>
    <table class="table table-bordered table-hover table-striped">
	<thead>
		<th><input type="checkbox" name="checkboxall" onClick="toggle(this)"></th>
		<th>No</th>
		<th>Produk</th>
		<!--<th>Decription</th>-->
		<th>Batch</th>
		<th>Hu Number</th>
		<th>Quantity</th>
		<th>No Truck</th>
		<th>Nama Supir</th>
	</thead>
	<tbody>
		<?php
		$no = 1;
		foreach ($modelsSugar as $model) {  ?>
			<tr id="rows[]">
				<td>
					<input type="checkbox" name="checkbox[]" id="checkbox" value="<?php echo $model['id']; ?>" />
				</td>
				<td><?php echo $no; ?></td>
				<td>
					<?php echo $model->produk; ?>
					<?php echo $form->field($model, 'produk[]')->hiddenInput([
						'value' => $model['produk'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<!--<td>
					<?php //echo $form->field($model, 'description[]')->textInput([
						//'value' => $model['description'],
						//'readOnly' => true
					//])->label(false) ?>
				</td>-->
				<td>
					<?php echo $model->batch; ?>
					<?php echo $form->field($model, 'batch[]')->hiddenInput([
						'value' => $model['batch'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->hu_number; ?>
					<?php echo $form->field($model, 'hu_number[]')->hiddenInput([
						'value' => $model['hu_number'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->quantity; ?>
					<?php echo $form->field($model, 'quantity[]')->hiddenInput([
						'value' => $model['quantity'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->no_pol; ?>
					<?php echo $form->field($model, 'no_pol[]')->hiddenInput([
						'value' => $model['no_pol'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->driver_name; ?>
					<?php echo $form->field($model, 'driver_name[]')->hiddenInput([
						'value' => $model['driver_name'],
						'readOnly' => true
					])->label(false) ?>
				</td>
			</tr>
		<?php $no++; } ?>
	</tbody>
</table>
<?php ActiveForm::end() ?>
<?php 
	echo \yii\widgets\LinkPager::widget([
		'pagination' => $pagesSugar,
	]);
?>

backend/views/site/outbound.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Outbound Finish Good');
$this->params['breadcrumbs'][] = $this->title;

?>
<script type="text/javascript">
	function toggle(pilih) {
	  	checkboxes = document.getElementsByName('checkbox[]');
	  	for (var i = 0, n=checkboxes.length;i<n;i++) {
	    	checkboxes[i].checked = pilih.checked;
	  	}
	}
	function toggleSugar(pilih) {
	  	checkboxes = document.getElementsByName('checkboxSugar[]');
	  	for (var i = 0, n=checkboxes.length;i<n;i++) {
	    	checkboxes[i].checked = pilih.checked;
	  	}
	}
</script>
<?php $form = ActiveForm::begin(); ?>
	<div class="form-group">
		<input type="text" class="form-control" name="no_sto" placeholder="Masukan Nomor STO" required>
	</div>
	<div class="form-group">
	<?= Html::submitButton('<i class="fa fa-spinner"></i>  Confirm', [ 'id' => 'update', 'class' => 'btn btn-primary btn-sm']) ?>
	<?= Html::submitButton('<i class="fa fa-refresh"></i>  Refresh', [ 'id' => 'update', 'class' => 'btn btn-default btn-sm']) ?>
	</div>
    <table class="table table-bordered table-hover table-striped">
	<thead>
		<th><input type="checkbox" name="checkboxall" onClick="toggle(this)"></th>
		<th>No</th>
		<th>Produk</th>
		<!--<th>Decription</th>-->
		<th>Batch</th>
		<th>Hu Number</th>
		<th>Quantity</th>
		<th>No Truck</th>
		<th>Nama Supir</th>
	</thead>
	<tbody>
		<?php
		$no = 1;
		foreach ($modelsFg as $model) {  ?>
			<tr id="rows[]">
				<td>
					<input type="checkbox" name="checkbox[]" id="checkbox" value="<?php echo $model['id']; ?>" />
				</td>
				<td><?php echo $no; ?></td>
				<td>
					<?php echo $model->produk; ?>
					<?php echo $form->field($model, 'produk[]')->hiddenInput([
						'value' => $model['produk'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<!--<td>
					<?php //echo $form->field($model, 'description[]')->textInput([
						//'value' => $model['description'],
						//'readOnly' => true
					//])->label(false) ?>
				</td>-->
				<td>
					<?php echo $model->batch; ?>
					<?php echo $form->field($model, 'batch[]')->hiddenInput([
						'value' => $model['batch'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->hu_number; ?>
					<?php echo $form->field($model, 'hu_number[]')->hiddenInput([
						'value' => $model['hu_number'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->quantity; ?>
					<?php echo $form->field($model, 'quantity[]')->hiddenInput([
						'value' => $model['quantity'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->no_pol; ?>
					<?php echo $form->field($model, 'no_pol[]')->hiddenInput([
						'value' => $model['no_pol'],
						'readOnly' => true
					])->label(false) ?>
				</td>
				<td>
					<?php echo $model->driver_name; ?>
					<?php echo $form->field($model, 'driver_name[]')->hiddenInput([
						'value' => $model['driver_name'],
						'readOnly' => true
					])->label(false) ?>
				</td>
			</tr>
		<?php $no++; } ?>
	</tbody>
</table>
<?php ActiveForm::end() ?>
<?php 
	echo \yii\widgets\LinkPager::widget([
		'pagination' => $pagesFg,
	]);
?>