frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\UploadForm;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'data', 'search', 'putway', 'putway_confirmation', 'index'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'data', 'search', 'putway','putway_confirmation', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        //return $this->goHome();
        return $this->redirect(['/site/login']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionUpload()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');

            if ($model->validate()) {
                $model->file->saveAs('uploads/'. $model->file->baseName.'.'.$model->file->extension);
            }
        }
        return $this->render('upload', [
            'model' => $model,
        ]);
    }

    public function actionSearch()
    {
        $searchModel = new \common\models\MasterDataSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $model = new \common\models\MasterData();

        return $this->render('search', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
    }

    public function actionSend($hu_number)
    {
        $model = \common\models\MasterData::find()->where(['hu_number' => $hu_number])->one();
        $count = \common\models\MasterData::find()->where(['status' => 'scan'])->count();
        $status = 'scan';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Sukses Kirim data');

            return $this->redirect(['/site/search']);
        } else {
            return $this->render('create', [
                    'model' => $model,
                    $model->status = $status,
                ]);
        }
    }

    public function actionData()
    {
        $data = \common\models\MasterData::find()->where(['status' => 'scan']);
        $countQuery = clone $data;
        $pages = new \yii\data\Pagination(['totalCount' => $countQuery->count()]);
        $models = $data->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        
        if (isset($_POST['checkbox'])) {
            $status = 'confirm';
            $no_pol = Yii::$app->request->post('no_pol');
            $nama_supir = Yii::$app->request->post('driver_name');
            foreach ($_POST['checkbox'] as $index => $checkbox) {
                $check = ($checkbox);
                $update = "UPDATE master_data SET status='$status', no_pol='$no_pol', driver_name='$nama_supir' WHERE id='$check' ";

                Yii::$app->db->createCommand($update)->execute();
            }
            $this->redirect(['/site/data']);
        }
        return $this->render('data', [
                'models' => $models,
                'pages' => $pages,
            ]);
    }
    public function actionPutway()
    {   
        $model = new \common\models\TabelPutway();

        if ($model->load(Yii::$app->request->post())) {
            $status = 'scan';
            $model->status = $status;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Sukses Putway');
                return $this->redirect(['/site/putway']);
            }
        } else {
            return $this->render('@backend/views/tabel-putway/create', [
                'model' => $model,
            ]);
        }
    }

    public function actionPutway_confirmation()
    {
        $models = \common\models\TabelPutway::find()->where(['status' => 'scan'])->all();
        //$count = clone $data;
        //$pages = new \yii\data\Pagination(['totalCount' => $count->count()]);
        //$models = $data->offset($pages->offset)
          //  ->limit($pages->limit)
            //->all();

        if (isset($_POST['checkbox'])) {
            $status = 'done';
            $refrence = Yii::$app->request->post('refrence');
            foreach ($_POST['checkbox'] as $key => $checkbox) {
                $check = ($checkbox);
                $update = "UPDATE tabel_putway SET status = '$status', refrence = '$refrence' WHERE putway_id = '$check' ";

                $query = \Yii::$app->db->createCommand($update)->execute();
            }
            if ($query) {
                $modelDo = new \common\models\MasterDo();
                $modelDo->no_do = $refrence;
                $modelDo->save();
            }
            $this->redirect(['/site/putway_confirmation']);
        }
        return $this->render('putway', [
                'models' => $models,
                //'pages' => $pages,
            ]);
    }

    public function actionEdit($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $status = 'scan';

frontend/views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\MasterData */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="master-data-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'produk')->textInput(['maxlength' => true, 'readOnly' => true])->label(false) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true, 'readOnly' => true])->label(false) ?>

    <?= $form->field($model, 'batch')->textInput(['maxlength' => true,'readOnly' => true])->label(false) ?>

    <?= $form->field($model, 'quantity')->textInput()->label(false) ?>

    <?= $form->field($model, 'status')->hiddenInput()->label(false) ?>

    <div class="form-group">
        <?= Html::submitButton('Input', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/site/_search.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin([
	'action' => ['search'], 
	'method' => 'get',
]); ?>

<?= $form->field($model, 'hu_number')->textInput(['class' => 'form-control', 'placeholder' => 'Masukan HU Number'])->label(false) ?>
<div class="form-group">
	<?= Html::submitButton('Search', ['class' => 'btn btn-primary']); ?>
</div>

<?php ActiveForm::end(); ?>

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\MasterData */

$this->title = Yii::t('app', ' Scanning confirmation');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Master Datas'), 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="master-data-create">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->renderAjax('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/site/data.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

$this->title = Yii::t('app', 'Data Scann');
//$this->params['breadcrumbs'][] = $this->title;
?>
<script type="text/javascript">
	function toggle(pilih) {
	  	checkboxes = document.getElementsByName('checkbox[]');
	  	for (var i = 0, n=checkboxes.length;i<n;i++) {
	    	checkboxes[i].checked = pilih.checked;
	  	}
	}
</script>
	<?php /*if (empty($models)) {
		echo "<div class='alert alert-danger'>
				<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
				<strong>Data Not Result</strong>
			</div>";
	}*/ ?>
	<h1><?= \yii\helpers\Html::encode($this->title); ?></h1>
	<?php $form = ActiveForm::begin(); ?>
		<div class="form-group">
			<?php 
				/*$truck = \common\models\Transporter::find()->all();
				$listTruck = \yii\helpers\ArrayHelper::map($truck, 'no_pol', 'no_pol');

				echo Select2::widget([
					'name' => 'no_pol',
					'data' => $listTruck,
					'value' => '',
					'options' => ['placeholder' => 'Pilih No Polisi'],
					'pluginOptions' => ['allowClear' => true],
				])*/
			?>
			<label>No Truck</label>
			<input type="text" class="form-control" name="no_pol" placeholder="No Truck" required>
		</div>
		<div class="form-group">
			<label>Nama Supir</label>
			<input type="text" class="form-control" name="driver_name" placeholder="Nama Supir" required>
		</div>
		<table class="table table-bordered table-hover table-striped">
			<thead>
				<th><input type="checkbox" name="checkboxall" onClick="toggle(this)"></th>
				<th>No</th>
				<!--<th>Produk</th>-->
				<!--<th>Decription</th>-->
				<th>Hu Number</th>
				<th>Batch</th>
				<th>Quantity</th>
			</thead>
			<tbody>
				<?php
				$no = 1;
				foreach ($models as $model) {  ?>
					<tr id="rows[]">
						<td>
							<input type="checkbox" name="checkbox[]" id="checkbox" value="<?php echo $model['id']; ?>" />
						</td>
						<td><?php echo $no; ?></td>
						<!--<td>
							<?php //echo $model->produk; ?>
							<?php //echo $form->field($model, 'produk[]')->hiddenInput([
								//'value' => $model['produk'],
								//'readOnly' => true
							//])->label(false) ?>
						</td>-->
						<!--<td>
							<?php //echo $form->field($model, 'description[]')->textInput([
								//'value' => $model['description'],
								//'readOnly' => true
							//])->label(false) ?>
						</td>-->
						<td>
							<?php echo $model->hu_number; ?>
							<?php echo $form->field($model, 'hu_number[]')->hiddenInput([
								'value' => $model['hu_number'],
								'readOnly' => true
							])->label(false) ?>
						</td>
						<td>
							<?php echo $model->batch; ?>
							<?php echo $form->field($model, 'batch[]')->hiddenInput([
								'value' => $model['batch'],
								'readOnly' => true
							])->label(false) ?>
						</td>
						<td>
							<?php echo $model->quantity; ?>
							<?php echo $form->field($model, 'quantity[]')->hiddenInput([
								'value' => $model['quantity'],
								'readOnly' => true
							])->label(false) ?>
						</td>
					</tr>
					
				<?php $no++; } ?>
			</tbody>
		</table>
		<div class="form-group">
        	<?= Html::submitButton('<i class="fa fa-spinner"></i>  Confirm', [ 'id' => 'update', 'class' => 'btn btn-primary']) ?>
    	</div>
	<?php ActiveForm::end() ?>
	<?php 
		echo \yii\widgets\LinkPager::widget([
			'pagination' => $pages,
		]);
	?>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">
    <div class="body-content">
        <div class="jumbotron">
            <h1>Congratulations!</h1>

            <p class="lead">You have successfully created your Yii-powered application.</p>

            <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
        </div>
    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <!--<div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>-->

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/putway.php
<?php 

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;

$this->title = Yii::t('app', 'Putway Confirm');
//$this->params['breadcrumbs'][] = $this->title;
?>
<script type="text/javascript">
	function toggle(pilih) {
	  	checkboxes = document.getElementsByName('checkbox[]');
	  	for (var i = 0, n=checkboxes.length;i<n;i++) {
	    	checkboxes[i].checked = pilih.checked;
	  	}
	}
</script>
<h1><?= \yii\helpers\Html::encode($this->title); ?></h1>
<?php $form = ActiveForm::begin() ?>
<div class="form-group">
	<input type="text" class="form-control" name="refrence" placeholder="Refrence" required >
</div>
<table class="table table-bordered table-hover table-striped">
	<thead>
		<th><input type="checkbox" name="checkboxall" onClick="toggle(this)"></th>
		<th>No</th>
		<th>Type Produk</th>
		<th>HU Number</th>
		<th>To Lokasi</th>
		<th>action</th>
	</thead>
	<tbody>
	<?php 
		$no = 1;
		foreach ($models as $model) { ?>
			<tr>
				<td><input type="checkbox" name="checkbox[]" id="checkbox" value="<?php echo $model['putway_id']; ?>" /></td>
				<td><?php echo $no; ?></td>
				<td><?php echo $model->type_produk; ?></td>
				<td><?php echo $model->hu_number; ?></td>
				<td><?php echo $model->to_lokasi.'-'.$model->to_row.$model->to_level; ?></td>
				<td><?= Html::a('edit',['/site/edit', 'id' => $model->putway_id]); ?></td>
			</tr>
		<?php $no++; } ?>
	</tbody>
</table>
<div class="form-group">
	<?= Html::submitButton('<i class="fa fa-spinner"></i>  Confirm', [ 'id' => 'update', 'class' => 'btn btn-primary']) ?>
</div>
<?php ActiveForm::end() ?>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/search.php
<?php 

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Search');
//$this->params['breadcrumbs'][] = $this->title;

?>
<h1><?= \yii\helpers\Html::encode($this->title); ?></h1>
<?php echo $this->render('_search', ['model' => $searchModel]); ?>
<?php 
	if($searchModel->hu_number != null){
		echo GridView::widget([
					'dataProvider' => $dataProvider,
					// 'filterModel' => $searchModel,
					'columns' => [
						[						
							'class' => 'yii\grid\ActionColumn',
							'header' => 'Actions',
							'buttons' => [
								'checkin' => function ($url,$model) {
									return Html::a(
										'<p>Next>></p>',
										//without delete action
										//['/checkin/checkin_security','transporter'=>$model->no_truck],
										//---------------------
										['/site/send','hu_number'=>$model->hu_number],
										[
											'title' => 'Check-IN',
										]
									);
								},
							],
							'template' => '{checkin}',
						],
							'produk',
							//'description',
							'quantity',
					],
				]);	
	}
	else{
		Yii::$app->session->setFlash('warning', 'Please Masukan HU Number');
	}
?>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/upload.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

<?= $form->field($model, 'file')->fileInput() ?>

<div class="form-group">
	<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end() ?>